### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by f41c0r** [nemerle/boomerang#40]
500 Internal Error?

http://www.downforeveryoneorjustme.com/http://boomerang.nemerle.eu/

Same issue for the doxygen documentation

**Comment by nemerle** [comment]
Thank's for the heads-up, should be up now.

**Comment by f41c0r** [comment]
Awesome, Thanks.

Might be worth having archive.org take a snapshot of it... although you can probably generate doxygen from source

**Comment by nemerle** [comment]
Yup, the 'site' is pretty much just a Jenkins instance that runs doxygen after successful builds :)
