### ISSUE TITLE
boomerang.nemerle.eu is down

### ISSUE THREAD

**Issue by pfalcon** [nemerle/boomerang#41]
> This repository is now connected to continous integration server: http://boomerang.nemerle.eu 

Throws 500 now.

What you're doing is very worthy, thanks. But please avoid results of your work being weak-linked on yourself, or results of your work will end up where original Boomerang is. There're 3rd-party CI services like Travis which take some burden (like server maintenance) off you, allowing to concentrate on real thing - hacking.

Thanks again.

**Comment by nemerle** [comment]
Thank You 
It's already up :)

As for Travis I've never set up any integration with it so it would take some time to do it correctly.
And taking into account the poor state of boomerang's test suite, boomerang.nemerle.eu is meant mainly as doxygen storage :)

**Comment by pfalcon** [comment]
Thanks.

As for Travis, we had similar situation in a project I contribute too, so we just waited until some guy came by and said: "Hey, it's easy, here's an example: ...". So, here's an example: https://github.com/micropython/micropython/blob/master/.travis.yml . I still never have read Travis docs, but I patched that file and it all still works ;-).
