### ISSUE TITLE
Begin Semantic versioning

### ISSUE THREAD

**Issue by hakusdream** [nemerle/boomerang#54]
#46 brings up a good point. Distros need to be able to package us consistently. [Semantic Versioning](http://semver.org/) would help.

Debian [knows us](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=440292) at 0.3.1.

I suggest we start at 0.4.

**Comment by nemerle** [comment]
Well, I've tagged a release as v0.3.99-alpha  I hope we can get a few more bugs fixed before v0.4.0 
I tentatively marked release date of v0.4.0 release as 25th of April

**Comment by hakusdream** [comment]
Noted. Thanks.
