### ISSUE TITLE
Store binaries in serialized project file

### ISSUE THREAD

**Issue by hakusdream** [nemerle/boomerang#58]
Any benefits of storing binaries in such way?

@nemerle A question label would be greatly appreciated.

**Comment by nemerle** [comment]
Boomerang should be more interactive, thus we want the user's work to be saved/loaded from disk.
So we either store loaded binary in our own serialization format, or use an multi-file archives (zip) as project files and store 'raw' files there.

**Comment by hakusdream** [comment]
In OS X, data is stored in a specially formatted folder, appearing as a file under Finder. (In the same folder as the binary.)

In Linux, data is stored in a workspace. (In the same folder as the binary.)

In Windows, data is saved in a program folder. (In the user's home directory, under AppData.)

**Comment by hakusdream** [comment]
Voting for a specific style would be a good idea.

**Comment by nemerle** [comment]
The location of storage of user-created Project files is platform/user specific thing, and the only way I plan on enforcing it, is using Qt Desktop services to provide initial paths in Save/Save As dialogs.

The internal format of the Project file should not depend on the host platform, and is the main point of this issue :smile:

**Comment by hakusdream** [comment]
Noted.
