### ISSUE TITLE
Fatal error: msvc_fixes.h: No such file or directory

### ISSUE THREAD

**Issue by Cinek75** [nemerle/boomerang#64]
Latest git repos.
Msys2  environment with gcc 6.2.0, mingw-w64-x86_64-toolchain.

$ make
[  0%] Automatic moc for target boom_base
[  0%] Built target boom_base_automoc
[  1%] Building CXX object CMakeFiles/boom_base.dir/loader/BinaryFileFactory.cpp.o
In file included from D:/Devel/boomerang/src/loader/BinaryFileFactory.cpp:10:0:
D:/Devel/boomerang/src/include/boomerang.h:31:24: fatal error: msvc_fixes.h: No such file or directory
 #include "msvc_fixes.h"
                        ^
compilation terminated.
make[2]: *** [CMakeFiles/boom_base.dir/build.make:63: CMakeFiles/boom_base.dir/loader/BinaryFileFactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/boom_base.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by Cinek75** [comment]
Add the following code in the files boomerang.h, chllcode.cpp fix the problem.

ifdef _MSC_VER
#include "msvc_fixes.h"
#endif

**Comment by nemerle** [comment]
This should be resolved by 90c88ed250777cfb840c8dcc2673382af3779f9f
